package(default_visibility = ["//visibility:public"])

exports_files([
    "range_check.h",
])

cc_library(
    name = "range_check",
    srcs = [
    ],
    hdrs = [
        "range_check.h",
        "//src/starkware/air/components:trace_generation_context.h",
        "//src/starkware/air/components:virtual_column.h",
        "//src/starkware/error_handling:error_handling.h",
        "//src/starkware/math:math.h",
        "//src/third_party/gsl:gsl-lite.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
    ],
)
