load("//src/starkware/air/degree_three_example:load_targets.bzl", "load_targets")

load_targets()

package(default_visibility = ["//visibility:public"])

exports_files([
    "degree_three_example_trace_context.h",
])
