cc_library(
    name = "starkware_common",
    srcs = [],
    hdrs = [],
    visibility = ["//visibility:public"],
    deps = [
        # Do not sort.
        "//src/starkware/utils:task_manager",
        "//src/starkware/error_handling",
        "//src/starkware/utils:to_from_string",
    ],
)
