package(default_visibility = ["//visibility:public"])

exports_files([
    "ec_subset_sum.h",
    "ec_subset_sum.inl",
])

cc_library(
    name = "ec_subset_sum",
    srcs = [
    ],
    hdrs = [
        "ec_subset_sum.h",
        "ec_subset_sum.inl",
        "//src/starkware/air/components:trace_generation_context.h",
        "//src/starkware/air/components:virtual_column.h",
        "//src/starkware/air/components/bit_unpacking:bit_unpacking.h",
        "//src/starkware/algebra:big_int.h",
        "//src/starkware/algebra:big_int.inl",
        "//src/starkware/algebra:field_element_base.h",
        "//src/starkware/algebra:field_element_base.inl",
        "//src/starkware/algebra:field_operations.h",
        "//src/starkware/algebra:field_operations.inl",
        "//src/starkware/algebra:uint128.h",
        "//src/starkware/algebra/elliptic_curve:elliptic_curve.h",
        "//src/starkware/algebra/elliptic_curve:elliptic_curve.inl",
        "//src/starkware/algebra/fields:fraction_field_element.h",
        "//src/starkware/algebra/fields:fraction_field_element.inl",
        "//src/starkware/crypt_tools:keccak_256.h",
        "//src/starkware/crypt_tools:keccak_256.inl",
        "//src/starkware/crypt_tools:utils.h",
        "//src/starkware/error_handling:error_handling.h",
        "//src/starkware/math:math.h",
        "//src/starkware/randomness:hash_chain.h",
        "//src/starkware/randomness:prng.h",
        "//src/starkware/stl_utils:containers.h",
        "//src/starkware/utils:attributes.h",
        "//src/starkware/utils:serialization.h",
        "//src/starkware/utils:serialization.inl",
        "//src/starkware/utils:to_from_string.h",
        "//src/third_party/gsl:gsl-lite.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
    ],
)
