package(default_visibility = ["//visibility:public"])

exports_files([
    "hash_component.h",
    "hash_factory.h",
])

cc_library(
    name = "hash",
    srcs = [
    ],
    hdrs = [
        "hash_component.h",
        "hash_factory.h",
        "//src/starkware/air/components:trace_generation_context.h",
        "//src/starkware/air/components:virtual_column.h",
        "//src/starkware/crypt_tools/hash_context:hash_context.h",
        "//src/starkware/error_handling:error_handling.h",
        "//src/starkware/math:math.h",
        "//src/third_party/gsl:gsl-lite.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
    ],
)
