package(default_visibility = ["//visibility:public"])

exports_files([
    "fibonacci_statement.h",
    "fibonacci_statement.inl",
])

cc_library(
    name = "fibonacci",
    srcs = [
    ],
    hdrs = [
        "fibonacci_statement.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
    ],
)
